DROP TABLE IF EXISTS list2task;
DROP TABLE IF EXISTS team2user;
DROP TABLE IF EXISTS team2list;
DROP TABLE IF EXISTS teams;

DROP TABLE IF EXISTS lists;
DROP TABLE IF EXISTS deadline_tasks;
DROP TABLE IF EXISTS recurrent_tasks;
DROP TABLE IF EXISTS highlighted_tasks;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS avatars;
DROP TABLE IF EXISTS themes;