version: '3.9'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo_list
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080